import { DeliveryMap } from '@/components/DeliveryMap';
import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowRight, Boxes, ChevronRight, ClipboardCheck, Download, Forklift, MapPin, PackageCheck, Thermometer, Truck, Warehouse } from 'lucide-react';

export const metadata: Metadata = {
  title: 'About Us | MAHAL FORET HAYAT',
  description: 'Learn about MAHAL FORET HAYAT, your construction material supply partner for product selection, technical documentation and site delivery planning.',
};

const pillars = [
  { number: '01', icon: PackageCheck, title: 'Authenticity you can check.', description: 'Ask for original packaging, batch identification and available manufacturer documentation with your material order.', detail: 'Traceability from product to project' },
  { number: '02', icon: Truck, title: 'Procurement that keeps pace.', description: 'Confirm product availability, quantities and delivery dates before committing your site schedule. Plan staged orders around your work sequence.', detail: 'Availability confirmed before dispatch' },
  { number: '03', icon: ClipboardCheck, title: 'Specifications, supported.', description: 'Identify the TDS, SDS and application guidance needed for your submittal. Request product-specific approvals for your project requirements.', detail: 'Documentation for informed decisions' },
  { number: '04', icon: Boxes, title: 'Orders built around your site.', description: 'Discuss bulk quantities, palletized orders and phased deliveries. Contractor accounts and credit terms are subject to assessment and approval.', detail: 'Commercial terms agreed per order' },
];

const ecosystems = [
  { name: 'Finishing & plaster systems', brand: 'VETONIT', image: 'plasters-masonry.png', alt: 'Vetoblock Mortar AAC product bag', description: 'Plasters, renders and finishes for masonry, interior walls and external facades.', applications: 'Base coats · Renders · Facade finishes', href: '/products/external-renders-vetonit' },
  { name: 'Waterproofing & joint sealing', brand: 'INSUWRAP', image: 'waterproofing.png', alt: 'Vetonit Cool Top waterproofing product', description: 'Explore membrane, coating and sealing systems for roofs and below-grade applications.', applications: 'Roofs · Basements · Wet areas', href: '/products/cementitious-slurry-coats' },
  { name: 'Flooring & concrete repair', brand: 'VETONIT', image: 'concrete-repairs.png', alt: 'Vetorep CR523 concrete repair product', description: 'Repair mortars, floor preparation and grouting systems matched to the application.', applications: 'Industrial floors · Structural repairs', href: '/products/structural-repair-mortars' },
  { name: 'Tile fixing technology', brand: 'VETONIT', image: 'tiling.png', alt: 'Vetonit Ceramic Tile Fix product bag', description: 'Adhesive and grout systems for ceramic, porcelain, stone and demanding installation conditions.', applications: 'Tile adhesives · Grouts · Preparation', href: '/products/ceramic-tile-fix' },
];

export default function AboutPage() {
  return (
    <div className="homepage bg-white text-neutral-900">
      <section aria-labelledby="about-title" className="relative isolate overflow-hidden bg-surface-dark text-white">
        <Image src="/images/warehouse.jpg" alt="Illustrative warehouse with organized pallet storage and loading areas" fill loading="eager" fetchPriority="high" sizes="100vw" className="object-cover object-[65%_center] opacity-50" />
        <div className="absolute inset-0 bg-gradient-to-r from-surface-dark via-surface-dark/85 to-surface-dark/20" />
        <div className="home-container relative pb-16 pt-8 sm:pb-20 lg:pb-24">
          <nav aria-label="Breadcrumb" className="mb-12 flex items-center gap-2 text-xs text-neutral-300 sm:mb-16"><Link href="/" className="hover:text-white">Home</Link><ChevronRight className="h-3 w-3" aria-hidden="true" /><span aria-current="page">About Us</span></nav>
          <div className="grid items-end gap-10 lg:grid-cols-[1.5fr_0.7fr]">
            <div><p className="mb-5 text-[11px] font-semibold uppercase tracking-[0.2em] text-brand-300">About MAHAL FORET HAYAT</p><h1 id="about-title" className="max-w-2xl text-[clamp(2.5rem,4vw,5rem)] font-semibold leading-[1.08] tracking-[-0.05em] text-balance"><span className="block text-[clamp(2.5rem,4vw,5rem)] font-semibold leading-[1.08] tracking-[-0.05em]">MAHAL FORET HAYAT</span><span className="mt-5 block text-xl font-medium leading-snug tracking-normal sm:text-2xl">Your material supply partner.</span><span className="mt-4 block text-xl font-medium leading-snug tracking-normal text-brand-400 sm:text-2xl">Aligned with your build.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-neutral-300 sm:text-lg">Construction materials, practical procurement and delivery planning. We help you move from an approved specification to a coordinated site order.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contact#quote" className="home-button bg-brand-700 text-white hover:bg-brand-800">Discuss your project<ArrowRight className="h-4 w-4" /></Link><a href="#partnership" className="home-button border border-white/30 hover:bg-white/10">How we work<ArrowDown className="h-4 w-4" /></a></div></div>
            <aside className="max-w-sm border-l-2 border-brand-400 bg-neutral-950/40 p-5 backdrop-blur-sm"><Warehouse className="mb-4 h-7 w-7 text-brand-400" strokeWidth={1.3} /><p className="text-lg font-medium">Built around the supply chain.</p><p className="mt-3 text-sm leading-6 text-neutral-300">Product selection. Documentation. Availability. Dispatch. A clear path from inquiry to site delivery.</p><p className="mt-4 border-t border-white/15 pt-3 text-xs leading-5 text-neutral-400">Talk with our team about your project location and material requirements.</p></aside>
          </div>
        </div>
        <p className="relative border-t border-white/10 bg-surface-dark/75 px-5 py-3 text-center text-[11px] text-neutral-400">Warehouse photography is illustrative. Company facility images will be added when available.</p>
      </section>

      <section id="partnership" className="home-container py-16 sm:py-20"><p className="home-eyebrow">About our company</p><h2 className="home-heading mt-3">Materials for your project.<br />Support at every step.</h2><div className="mt-8 grid gap-6 md:grid-cols-2"><article className="border border-neutral-200 bg-neutral-50 p-7"><h3 className="text-xl font-semibold">The right material for the task.</h3><p className="mt-4 text-sm leading-7 text-neutral-500">MAHAL FORET HAYAT brings construction material systems together in one place. Explore tiling, waterproofing, flooring, repair and finishing options, with guidance on applications and technical documentation.</p><Link href="/products" className="mt-6 inline-flex items-center gap-2 text-sm text-brand-700">Explore our products<ArrowRight className="h-4 w-4" /></Link></article><article className="bg-surface-dark p-7 text-white"><h3 className="text-xl font-semibold">A conversation built around your site.</h3><p className="mt-4 text-sm leading-7 text-neutral-300">Share your specification, project location and preferred schedule. Our team helps you review material requirements, supporting documents and delivery planning.</p><Link href="/contact#quote" className="mt-6 inline-flex items-center gap-2 text-sm text-brand-300">Discuss your project<ArrowRight className="h-4 w-4" /></Link></article></div></section>

      <section id="values" className="border-y border-neutral-200 bg-surface py-16 sm:py-20"><div className="home-container"><p className="home-eyebrow">Why contractors source with us</p><div className="mt-3 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="home-heading">Confidence in every step.</h2><p className="max-w-sm text-sm leading-6 text-neutral-500">Clear expectations, product traceability and practical support for your procurement team.</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{pillars.map((pillar) => <article key={pillar.number} className="flex flex-col border border-neutral-200 bg-white p-6"><div className="flex items-center justify-between"><pillar.icon className="h-7 w-7 text-brand-700" strokeWidth={1.4} /><span className="font-mono text-xs text-neutral-400">{pillar.number}</span></div><h3 className="mt-7 text-lg font-semibold leading-6 tracking-tight">{pillar.title}</h3><p className="mb-6 mt-3 text-sm leading-6 text-neutral-500">{pillar.description}</p><p className="mt-auto border-t border-neutral-100 pt-4 text-xs font-medium leading-5 text-brand-700">{pillar.detail}</p></article>)}</div></div></section>

      <section id="ecosystem" className="home-container py-16 sm:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="home-eyebrow">The technology ecosystem</p><h2 className="home-heading mt-3">One portfolio.<br />Different jobs. Complete systems.</h2></div><Link href="/#solutions" className="inline-flex items-center gap-2 text-sm font-medium text-brand-700">Browse all solution families<ArrowRight className="h-4 w-4" /></Link></div><div className="mt-9 grid gap-5 md:grid-cols-2">{ecosystems.map((item) => <a key={item.name} href={item.href} className="group grid overflow-hidden border border-neutral-200 transition-colors hover:border-brand-400 sm:grid-cols-[145px_1fr]"><div className="flex min-h-40 items-center justify-center bg-surface-muted p-4"><Image src={`/images/${item.image}`} alt={item.alt} width={120} height={150} className="h-36 w-28 object-contain transition-transform duration-300 group-hover:scale-105" /></div><div className="flex flex-col p-5 sm:p-6"><p className="text-[10px] font-semibold tracking-[0.15em] text-brand-700">{item.brand}</p><h3 className="mt-2 text-lg font-semibold leading-6 tracking-tight">{item.name}</h3><p className="mt-3 text-sm leading-6 text-neutral-500">{item.description}</p><div className="mt-5 flex items-start justify-between gap-3 text-xs leading-5 text-neutral-500"><span>{item.applications}</span><ArrowRight className="h-4 w-4 shrink-0 text-brand-700" /></div></div></a>)}</div><p className="mt-5 text-xs leading-5 text-neutral-500">System suitability depends on the substrate, exposure and specification. Refer to the current manufacturer documentation for the selected product.</p></section>

      <section id="capabilities" className="bg-surface-dark py-16 text-white sm:py-20"><div className="home-container grid gap-10 lg:grid-cols-2 lg:gap-16"><div><p className="home-eyebrow !text-brand-400">Warehousing & delivery planning</p><h2 className="home-heading mt-3">A good order is only<br />complete when it reaches site.</h2><p className="mt-5 text-sm leading-7 text-neutral-300">Tell us where your project is, how materials need to be stored and what offloading access is available. These details shape a practical delivery plan.</p><figure className="mt-7"><div className="relative aspect-[16/10] overflow-hidden"><Image src="/images/warehouse.jpg" alt="Illustrative covered warehouse storage racks" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /></div><figcaption className="mt-2 text-[10px] text-neutral-400">Illustrative facility image; not a photograph of company premises.</figcaption></figure></div><div className="space-y-0 self-center">{[{ icon: Warehouse, title: 'Covered storage footprint', text: 'Warehouse locations and covered square meters are pending confirmation. Request the storage details applicable to your order.', status: 'Capacity to be confirmed' }, { icon: Thermometer, title: 'Product-aware storage', text: 'Polymers, grouts and liquid systems require product-specific storage conditions. Climate-control availability must be confirmed for the selected materials.', status: 'Conditions checked against product TDS' }, { icon: Forklift, title: 'Transport & offloading', text: 'Discuss pallet sizes, truck access and offloading arrangements. Vehicle types, forklifts and lifting equipment are agreed before dispatch.', status: 'Fleet and equipment subject to confirmation' }, { icon: MapPin, title: 'Geographic reach & turnaround', text: 'Share your site location and preferred delivery window. Service radius and lead time are confirmed with the final order.', status: 'Territory and dispatch times to be confirmed' }].map((item) => <div key={item.title} className="flex gap-4 border-b border-white/15 py-6 first:pt-0"><item.icon className="mt-1 h-6 w-6 shrink-0 text-brand-400" strokeWidth={1.4} /><div><h3 className="text-base font-medium">{item.title}</h3><p className="mt-2 text-sm leading-6 text-neutral-300">{item.text}</p><p className="mt-3 text-[11px] text-brand-300">{item.status}</p></div></div>)}</div></div></section>

      <section className="home-container py-12"><DeliveryMap /></section>
      <section id="quality" className="home-container py-16"><p className="home-eyebrow">Technical support</p><h2 className="home-heading mt-3">Information for confident decisions.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-neutral-500">Request current technical data, safety information and application guidance for the materials in your specification. Product approvals are reviewed against your project requirements.</p><Link href="/#resources" className="mt-6 inline-flex items-center gap-2 text-sm text-brand-700">Explore technical resources<ArrowRight className="h-4 w-4" /></Link></section>

      <section id="contractor-inquiry" className="border-y border-neutral-200 bg-surface py-14 sm:py-16"><div className="home-container flex flex-col justify-between gap-8 lg:flex-row lg:items-center"><div className="max-w-2xl"><p className="home-eyebrow">Your next project</p><h2 className="home-heading mt-3">Build a dependable supply plan.<br />Start with a conversation.</h2><p className="mt-4 text-sm leading-7 text-neutral-500">Discuss a contractor account, share your BOQ or request a quote. Account approval, availability and commercial terms are confirmed individually.</p></div><div className="flex shrink-0 flex-col gap-4"><Link href="/contact#quote" className="home-button bg-brand-700 text-white hover:bg-brand-800">Contractor account / Request quote<ArrowRight className="h-4 w-4 shrink-0" /></Link><a href="/company-profile.pdf" download className="inline-flex items-center justify-center gap-2 text-sm font-medium text-brand-700 hover:text-brand-900"><Download className="h-4 w-4" />Download company profile (PDF)</a><p className="text-center text-[11px] text-neutral-500">Draft profile · business details awaiting confirmation</p></div></div></section>
    </div>
  );
}
