'use client';

import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { MapPin, Search } from 'lucide-react';
import { deliveryLocations } from '@/lib/delivery-locations';

export function DeliveryMap({ compact = false }: { compact?: boolean }) {
  const [query, setQuery] = useState('');
  const [destination, setDestination] = useState(deliveryLocations[0]?.address ?? '');
  const confirmed = deliveryLocations.find(location => location.address === destination);
  function search(event: FormEvent) { event.preventDefault(); if (query.trim()) setDestination(query.trim()); }
  const src = destination ? `https://maps.google.com/maps?q=${encodeURIComponent(destination)}&output=embed` : 'https://www.openstreetmap.org/export/embed.html?bbox=-180%2C-60%2C180%2C80&layer=mapnik';
  return <div className={compact ? 'space-y-4' : 'grid gap-6 lg:grid-cols-[0.7fr_1.3fr]'}>
    <div><p className="flex items-center gap-2 text-sm font-semibold"><MapPin className="h-4 w-4 text-brand-700" />Delivery & locations</p><p className="mt-3 text-xs leading-6 text-neutral-500">{deliveryLocations.length ? 'Select a delivery area or company location to explore the map.' : 'Confirmed delivery areas and company addresses are awaiting your business details. You can explore a project location below.'}</p><form onSubmit={search} className="mt-4 flex gap-2"><label className="sr-only" htmlFor={compact ? 'footer-map-search' : 'delivery-map-search'}>Project city or address</label><input id={compact ? 'footer-map-search' : 'delivery-map-search'} value={query} onChange={event => setQuery(event.target.value)} maxLength={250} placeholder="City or project address" className="home-input min-w-0 flex-1 bg-white text-neutral-800" /><button type="submit" disabled={!query.trim()} aria-label="Explore location on map" className="rounded-xl bg-brand-700 px-3 text-white disabled:opacity-40"><Search className="h-4 w-4" /></button></form>{query.trim() && <div aria-label="Location search results" className="mt-2 rounded-xl border border-neutral-200 bg-white p-3"><p className="text-xs text-neutral-500">Explore this location on the map</p><button type="button" onClick={() => setDestination(query.trim())} className="mt-2 flex w-full items-center gap-2 py-3 text-left text-sm text-brand-700"><MapPin className="h-4 w-4 shrink-0" />{query.trim()}</button><p className="text-[11px] leading-5 text-neutral-500">Location lookup only; delivery coverage is confirmed separately.</p></div>}<div className="mt-4 space-y-2">{deliveryLocations.map(location => <button type="button" key={location.address} aria-pressed={destination === location.address} onClick={() => setDestination(location.address)} className={`block w-full rounded-xl border p-3 text-left text-xs ${destination === location.address ? 'border-brand-600 bg-brand-50 text-brand-800' : 'border-neutral-200'}`}><span className="block font-semibold">{location.name}</span><span className="mt-1 block">{location.kind} / {location.address}</span></button>)}</div>{destination && <p aria-live="polite" className="mt-4 text-xs leading-6 text-neutral-500">{confirmed ? `${confirmed.kind}: ${confirmed.name}` : 'Exploring a project location. This search does not confirm delivery availability.'}</p>}<Link href="/contact#quote" className="mt-4 inline-block text-xs font-semibold text-brand-700">Ask about delivery to your site →</Link></div>
    <div className="min-w-0"><iframe key={src} src={src} title={destination ? `Interactive map of ${destination}` : 'Interactive world map for project location planning'} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen className={`w-full rounded-2xl border border-neutral-200 bg-neutral-100 ${compact ? 'h-60' : 'h-80 sm:h-[420px]'}`} /><div className="mt-3 flex flex-wrap justify-between gap-2 text-[11px] text-neutral-500"><span>Pan and zoom to explore the location.</span></div></div>
  </div>;
}
