'use client';

import { useId, useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Calculator, Check, ChevronRight, FileText, Package, ShieldCheck, Truck, X, ZoomIn } from 'lucide-react';
import { QuoteForm } from './HomeInteractions';

const tabs = ['Technical specs', 'Application guide', 'Approvals & standards', 'Packaging & storage'];
const gallery = [
  { label: 'Product bag', src: '/images/tiling.png', alt: 'Vetonit Ceramic Tile Fix 20 kg bag', zoom: false },
  { label: 'Packaging detail', src: '/images/tiling.png', alt: 'Enlarged front packaging detail of Ceramic Tile Fix', zoom: true },
  { label: 'Application', src: '/images/tiling-application.jpg', alt: 'Manufacturer illustration of a tiling application', zoom: false },
];
const specs = [
  ['Product type', 'Cementitious tile adhesive'],
  ['Composition', 'Hydraulic binders, aggregates and additives'],
  ['Application thickness', '3–10 mm'],
  ['20 kg mixing water', '5.2–6.8 liters'],
  ['25 kg mixing water', '6.5–8.5 liters'],
  ['Working life', '2–2.5 hours'],
  ['Adjustment window', '10–15 minutes'],
  ['Before disturbing installation', 'At least 48 hours'],
];

export function ProductDetail() {
  const [imageIndex, setImageIndex] = useState(0);
  const [tab, setTab] = useState(0);
  const [area, setArea] = useState('250');
  const [rate, setRate] = useState('3.5');
  const [waste, setWaste] = useState('0');
  const lightboxRef = useRef<HTMLDialogElement>(null);
  const tabRefs = useRef<(HTMLButtonElement | null)[]>([]);
  const tabId = useId();
  const bagWeight = 20;
  const validEstimate = area !== '' && rate !== '' && waste !== '' && Number(area) > 0 && Number(area) <= 1000000 && Number(rate) > 0 && Number(rate) <= 100 && Number(waste) >= 0 && Number(waste) <= 100;
  const kilograms = validEstimate ? Number(area) * Number(rate) * (1 + Number(waste) / 100) : 0;
  const estimatedBags = Math.ceil(kilograms / bagWeight);
  const number = (value: number) => value.toLocaleString('en', { maximumFractionDigits: 1 });

  function requestQuote(extra = '') {
    window.dispatchEvent(new CustomEvent('quote-prefill', { detail: ('Product inquiry: Vetonit Ceramic Tile Fix\n' + extra).trim() }));
    document.getElementById('product-quote')?.scrollIntoView({ behavior: 'auto', block: 'start' });
  }

  return <div className="homepage bg-white text-neutral-900">
    <div className="border-b border-neutral-200 bg-neutral-50"><div className="home-container py-5"><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-xs leading-5 text-neutral-500"><Link href="/">Home</Link><ChevronRight className="h-3 w-3" /><Link href="/products">Products</Link><ChevronRight className="h-3 w-3" /><Link href="/products">Tile & stone fixing</Link><ChevronRight className="h-3 w-3" /><span aria-current="page" className="text-neutral-800">Ceramic Tile Fix</span></nav></div></div>
    <section className="home-container grid gap-9 py-10 sm:py-14 lg:grid-cols-[0.95fr_1.05fr] lg:gap-14">
      <div className="min-w-0">
        <div className="relative flex h-[360px] items-center justify-center overflow-hidden border border-neutral-200 bg-surface-muted sm:h-[440px]">
          <span className="absolute left-5 top-5 z-10 bg-white px-3 py-1.5 text-[10px] font-semibold uppercase tracking-widest text-brand-700">Product showcase</span>
          <Image src={gallery[imageIndex].src} alt={gallery[imageIndex].alt} width={650} height={650} priority className={imageIndex === 2 ? 'h-full w-full object-cover' : `h-[75%] w-[75%] object-contain ${gallery[imageIndex].zoom ? 'scale-150' : ''}`} />
          <button type="button" aria-label="Enlarge product image" onClick={() => lightboxRef.current?.showModal()} className="absolute bottom-4 right-4 bg-white p-3 text-neutral-600 hover:text-brand-700"><ZoomIn className="h-5 w-5" /></button>
        </div>
        <div className="mt-3 grid grid-cols-3 gap-3">{gallery.map((image, index) => <button key={image.label} type="button" aria-pressed={imageIndex === index} onClick={() => setImageIndex(index)} className={`min-w-0 border bg-white p-2 text-center ${imageIndex === index ? 'border-brand-700 ring-1 ring-brand-700' : 'border-neutral-200 hover:border-neutral-400'}`}><Image src={image.src} alt="" width={100} height={75} className="mx-auto h-16 w-20 object-contain" /><span className="mt-2 block text-[10px] text-neutral-500">{image.label}</span></button>)}</div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => requestQuote('Please share the current technical data sheet.')} className="home-button border border-neutral-200 text-neutral-700 hover:border-brand-600"><FileText className="h-4 w-4 text-brand-700" />Request TDS<ArrowRight className="h-3.5 w-3.5" /></button><button type="button" onClick={() => requestQuote('Document request: current SDS for Ceramic Tile Fix.')} className="home-button border border-neutral-200 text-neutral-700 hover:border-brand-600 disabled:opacity-50"><ShieldCheck className="h-4 w-4 text-brand-700" />Request SDS<ArrowRight className="h-3.5 w-3.5" /></button></div>
        <p className="mt-3 text-[11px] leading-5 text-neutral-500">Request the current technical and safety documents for your project.</p>
      </div>
      <div className="min-w-0"><p className="home-eyebrow">MAHAL FORET HAYAT / Product supply</p><h1 className="mt-3 text-[clamp(2rem,3.5vw,3.25rem)] font-semibold leading-[1.1] tracking-[-0.04em]">Vetonit<br />Ceramic Tile Fix</h1><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-neutral-500"><span>Brand: <strong className="font-medium text-neutral-700">Vetonit</strong></span><span>Category: Tile & stone fixing</span></div><p className="mt-5 text-sm leading-7 text-neutral-600">Cement-based adhesive for internal ceramic and terrazzo tile installations. Review application guidance and discuss suitability for your project.</p><div className="mt-5 flex flex-wrap gap-3 text-xs text-neutral-500">{['Water-mixed powder', 'Internal walls & floors', 'Slip-resistant adhesive'].map(text => <span key={text} className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-brand-700" />{text}</span>)}</div>
        <div className="mt-7 border-y border-neutral-200 py-5"><p className="text-xs font-semibold uppercase tracking-wider text-neutral-500">Product information</p><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-neutral-500">Packaging</dt><dd className="mt-1 font-medium">20 kg / 25 kg bags</dd></div><div><dt className="text-neutral-500">Application</dt><dd className="mt-1 font-medium">Internal walls & floors</dd></div></dl></div>
        <button type="button" onClick={() => requestQuote()} className="home-button mt-6 w-full bg-brand-700 text-white hover:bg-brand-800">Enquire about this product<ArrowRight className="h-4 w-4" /></button><button type="button" onClick={() => requestQuote('Please share the current TDS, SDS and applicable technical approvals.')} className="home-button mt-3 w-full border border-neutral-300 text-neutral-700 hover:border-brand-600">Request technical documents<FileText className="h-4 w-4" /></button>

      </div>
    </section>

    <section className="home-container pb-12"><div className="border border-neutral-200"><div role="tablist" aria-label="Product information" className="grid grid-cols-2 border-b border-neutral-200 bg-neutral-50 md:grid-cols-4">{tabs.map((label, index) => <button key={label} ref={node => { tabRefs.current[index] = node; }} type="button" role="tab" id={`${tabId}-tab-${index}`} aria-selected={tab === index} aria-controls={`${tabId}-panel-${index}`} tabIndex={tab === index ? 0 : -1} onClick={() => setTab(index)} onKeyDown={event => { let next = index; if (event.key === 'ArrowRight') next = (index + 1) % tabs.length; else if (event.key === 'ArrowLeft') next = (index + tabs.length - 1) % tabs.length; else if (event.key === 'Home') next = 0; else if (event.key === 'End') next = tabs.length - 1; else return; event.preventDefault(); setTab(next); tabRefs.current[next]?.focus(); }} className={`border-b-2 px-3 py-4 text-xs font-medium sm:text-sm ${tab === index ? 'border-brand-700 bg-white text-brand-700' : 'border-transparent text-neutral-500 hover:text-neutral-800'}`}>{label}</button>)}</div>
      {tabs.map((_, index) => <div key={index} role="tabpanel" id={`${tabId}-panel-${index}`} aria-labelledby={`${tabId}-tab-${index}`} hidden={tab !== index} tabIndex={0} className="p-5 sm:p-8">
        {index === 0 && <div className="grid gap-7 lg:grid-cols-[1.4fr_0.6fr]"><div><h2 className="text-xl font-semibold tracking-tight">Technical parameters</h2><table className="mt-5 w-full text-left text-xs sm:text-sm"><caption className="sr-only">Manufacturer-published Ceramic Tile Fix parameters</caption><tbody>{specs.map(([label, value]) => <tr key={label} className="border-b border-neutral-200"><th scope="row" className="w-1/2 py-3 pr-3 font-medium text-neutral-600">{label}</th><td className="py-3 text-neutral-800">{value}</td></tr>)}</tbody></table></div><aside className="h-fit bg-neutral-50 p-5"><FileText className="mb-4 h-6 w-6 text-brand-700" /><h3 className="text-sm font-semibold">Check the current TDS</h3><p className="mt-3 text-xs leading-6 text-neutral-500">Adhesion strength, open time, service temperature and product classification should be confirmed against the current technical sheet for the supplied variant.</p><button type="button" onClick={() => requestQuote('Please share the current technical data sheet.')} className="mt-4 inline-flex items-center gap-2 text-xs font-medium text-brand-700">Request technical information<ArrowRight className="h-3.5 w-3.5" /></button></aside></div>}
        {index === 1 && <div><h2 className="text-xl font-semibold">Application sequence</h2><ol className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['Prepare', 'Clean and dampen the substrate without leaving standing water.'], ['Mix', 'Mix at the specified ratio, rest about 10 minutes, then remix.'], ['Apply', 'Use a notched trowel and work within the stated adjustment window.'], ['Protect', 'Leave tiles undisturbed for at least 48 hours.']].map(([title, description], order) => <li key={title} className="border-l-2 border-brand-600 pl-4"><span className="font-mono text-xs text-neutral-400">0{order + 1}</span><h3 className="mt-3 text-sm font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-neutral-500">{description}</p></li>)}</ol><p className="mt-6 text-xs text-neutral-500">Follow the complete manufacturer instructions for the selected substrate and conditions.</p></div>}
        {index === 2 && <div className="max-w-3xl"><h2 className="text-xl font-semibold">Standards & project approvals</h2><p className="mt-4 text-sm leading-7 text-neutral-500">EN 12004 classifications, SASO requirements, test reports and environmental declarations need product-specific evidence. The example C1T, strength and VOC claims in the wireframe are not published here as verified certification.</p><button type="button" onClick={() => requestQuote('Please supply applicable standards, classification evidence and project approval documentation.')} className="home-button mt-6 border border-neutral-300 text-brand-700">Request approval package<ArrowRight className="h-4 w-4" /></button></div>}
        {index === 3 && <div><h2 className="text-xl font-semibold">Packaging & storage</h2><div className="mt-5 grid gap-5 sm:grid-cols-3">{[['Pack sizes', '20 kg and 25 kg bags; pallet arrangement confirmed with your quote.'], ['Storage requirements', 'Confirm shelf life and storage limits against the current TDS and bag label.'], ['Handling details', 'Pallet dimensions, gross weight and offloading arrangements confirmed before dispatch.']].map(([title, description]) => <div key={title} className="border border-neutral-200 p-5"><Package className="mb-4 h-5 w-5 text-brand-700" /><h3 className="text-sm font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-neutral-500">{description}</p></div>)}</div></div>}
      </div>)}
    </div></section>

    <section id="coverage" className="border-y border-neutral-200 bg-neutral-50 py-12"><div className="home-container grid gap-8 lg:grid-cols-[1.3fr_0.7fr]"><div><p className="home-eyebrow">Material planning tool</p><h2 className="mt-3 flex items-center gap-3 text-2xl font-semibold tracking-tight"><Calculator className="h-6 w-6 text-brand-700" />Coverage / quantity estimator</h2><p className="mt-3 text-sm leading-6 text-neutral-500">Set your area and assumed consumption. These rates are editable planning estimates, not manufacturer coverage guarantees.</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><label className="home-label">Surface area (m²)<input id="coverage-area" type="number" min="0.1" max="1000000" step="0.1" value={area} onChange={event => setArea(event.target.value)} className="home-input mt-2" /></label><label className="home-label">Planning rate (kg/m²)<input id="coverage-rate" type="number" min="0.1" max="100" step="0.1" value={rate} onChange={event => setRate(event.target.value)} className="home-input mt-2" /></label><label className="home-label">Waste allowance (%)<input id="coverage-waste" type="number" min="0" max="100" step="1" value={waste} onChange={event => setWaste(event.target.value)} className="home-input mt-2" /></label></div><label className="home-label mt-4 block">Trowel planning preset<select aria-label="Trowel planning preset" className="home-input mt-2" value={['2.5', '3.5', '5'].includes(rate) ? rate : 'custom'} onChange={event => { if (event.target.value !== 'custom') setRate(event.target.value); }}><option value="2.5">4 mm notch · assume 2.5 kg/m²</option><option value="3.5">6 mm notch · assume 3.5 kg/m²</option><option value="5">8 mm notch · assume 5 kg/m²</option><option value="custom">Custom consumption rate</option></select></label></div><div className="flex flex-col justify-center bg-surface-dark p-7 text-white"><p className="text-[10px] font-semibold uppercase tracking-widest text-brand-400">Planning estimate / {bagWeight} kg bags</p><div aria-live="polite" className="mt-4">{validEstimate ? <><p className="text-4xl font-semibold tracking-tight">{number(kilograms)} <span className="text-lg font-normal text-neutral-400">kg</span></p><p className="mt-3 text-lg text-neutral-300">Approx. {number(estimatedBags)} bags</p></> : <p className="text-sm leading-6 text-neutral-300">Enter a positive area and rate, and a waste allowance from 0–100%.</p>}</div><button type="button" disabled={!validEstimate} onClick={() => requestQuote(`Planning estimate: ${estimatedBags} bags (20 kg). Area: ${area} m? at ${rate} kg/m?, ${waste}% waste allowance; subject to site conditions.`)} className="home-button mt-6 border border-white/30 hover:bg-white/10 disabled:opacity-40">Use estimate in my inquiry<ArrowRight className="h-4 w-4" /></button></div></div></section>

    <section className="home-container py-14"><p className="home-eyebrow">Complementary material systems</p><h2 className="home-heading mt-3">Complete your specification.</h2><div className="mt-7 grid gap-4 sm:grid-cols-3">{[{ name: 'Tile grouts', text: 'Explore grouting options for the selected tile and joint.', image: 'tiling.png', query: 'Vetonit Tile Grout' }, { name: 'Bonding agents & primers', text: 'Review substrate preparation and bonding requirements.', image: 'plasters-masonry.png', query: 'Vetonit Bond 2' }, { name: 'Waterproofing systems', text: 'Consider the required wet-area waterproofing specification.', image: 'waterproofing.png', query: 'Vetoproof' }].map(item => <Link key={item.name} href={`/products/${item.name === 'Tile grouts' ? 'cementitious-tile-grouts' : item.name === 'Bonding agents & primers' ? 'bonding-agents' : 'cementitious-slurry-coats'}`} className="flex flex-col border border-neutral-200 p-5 hover:border-brand-600"><div className="mb-5 flex h-32 items-center justify-center bg-neutral-50"><Image src={`/images/${item.image}`} alt="Representative material system packaging" width={100} height={120} className="h-28 w-24 object-contain" /></div><h3 className="text-sm font-semibold">{item.name}</h3><p className="mt-2 text-xs leading-6 text-neutral-500">{item.text}</p><span className="mt-4 inline-flex items-center gap-2 text-xs text-brand-700">Explore product range<ArrowRight className="h-3.5 w-3.5" /></span></Link>)}</div><p className="mt-4 text-[11px] text-neutral-500">Representative images show material families. Confirm system compatibility with manufacturer guidance.</p></section>
    <section id="product-quote" className="border-t border-neutral-200 bg-neutral-50 py-14"><div className="home-container grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="home-eyebrow">Product inquiry</p><h2 className="home-heading mt-3">Let?s discuss your project.</h2><p className="mt-5 text-sm leading-7 text-neutral-500">Ask about product suitability, technical documentation or supply for your project. You can include a specification or BOQ for our team to review.</p><p className="mt-6 flex items-center gap-3 text-sm text-neutral-600"><Truck className="h-5 w-5 text-brand-700" />Delivery and offloading planned per order</p></div><QuoteForm /></div></section>
    <dialog ref={lightboxRef} aria-label="Enlarged product image" onClick={event => { if (event.target === event.currentTarget) lightboxRef.current?.close(); }} className="m-auto w-[min(90vw,800px)] max-w-none border border-neutral-200 bg-white p-5 backdrop:bg-neutral-900/70"><div className="flex justify-end"><button type="button" aria-label="Close enlarged image" onClick={() => lightboxRef.current?.close()} className="p-2"><X className="h-5 w-5" /></button></div><Image src={gallery[imageIndex].src} alt={gallery[imageIndex].alt} width={800} height={800} className="h-[65dvh] w-full object-contain" /><p className="mt-3 text-center text-xs text-neutral-500">{gallery[imageIndex].label}</p></dialog>
  </div>;
}
