'use client';

import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check, FileText } from 'lucide-react';
import type { ProductOverview as Overview } from '@/lib/products';
import { products } from '@/lib/products';
import { QuoteForm } from './HomeInteractions';

export function ProductOverview({ product }: { product: Overview }) {
  function inquire(documents = false) {
    window.dispatchEvent(new CustomEvent('quote-prefill', { detail: `${documents ? 'Technical document request' : 'Product inquiry'}: ${product.name}${documents ? '\nPlease share current TDS, SDS and application guidance.' : ''}` }));
    document.getElementById('overview-inquiry')?.scrollIntoView({ behavior: 'smooth' });
  }
  return <div className="homepage text-neutral-900">
    <div className="border-b border-neutral-200 bg-neutral-50"><nav aria-label="Breadcrumb" className="home-container flex flex-wrap gap-3 py-5 text-xs text-neutral-500"><Link href="/">Home</Link><span>/</span><Link href="/products">Products</Link><span>/</span><span aria-current="page">{product.name}</span></nav></div>
    <section className="home-container grid gap-10 py-12 lg:grid-cols-2"><figure className="border border-neutral-200 bg-neutral-50 p-8"><Image src={`/images/${product.image}`} alt={product.family ? `Representative ${product.category} packaging` : `${product.name} packaging`} width={500} height={500} priority className="mx-auto h-72 w-full object-contain sm:h-96" />{product.family && <figcaption className="mt-5 text-center text-xs text-neutral-500">Representative material-family image.</figcaption>}</figure><div className="self-center"><p className="home-eyebrow">MAHAL FORET HAYAT / {product.family ? 'Material family' : 'Product overview'}</p><p className="mt-5 text-xs font-medium text-brand-700">{product.category}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">{product.name}</h1><p className="mt-5 text-sm leading-7 text-neutral-600">{product.description}</p><ul className="mt-6 space-y-3">{product.features.map(feature => <li key={feature} className="flex gap-2 text-sm text-neutral-600"><Check className="h-4 w-4 shrink-0 text-brand-700" />{feature}</li>)}</ul><div className="mt-6 border-l-2 border-brand-400 bg-neutral-50 p-4"><p className="text-lg font-semibold">Price on request</p><p className="mt-1 text-xs leading-6 text-neutral-500">Request current pricing for your quantity and delivery location.</p></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={() => inquire()} className="home-button bg-brand-700 text-white">Enquire about this {product.family ? 'system' : 'product'}<ArrowRight className="h-4 w-4" /></button><button onClick={() => inquire(true)} className="home-button border border-neutral-300"><FileText className="h-4 w-4" />Request documents</button></div></div></section>
    <section className="border-y border-neutral-200 bg-neutral-50 py-12"><div className="home-container grid gap-9 lg:grid-cols-2"><div><p className="home-eyebrow">Applications</p><h2 className="home-heading mt-3">Where it is used.</h2><ul className="mt-6 space-y-4">{product.uses.map(use => <li key={use} className="border-b border-neutral-200 pb-3 text-sm leading-6 text-neutral-600">{use}</li>)}</ul></div><div><h2 className="text-xl font-semibold">Technical overview</h2><dl className="mt-5">{product.facts.map(([label,value]) => <div key={label} className="grid grid-cols-2 gap-4 border-b border-neutral-200 py-4 text-sm"><dt className="text-neutral-500">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl><p className="mt-5 text-xs leading-6 text-neutral-500">Confirm the current technical sheet, product variant, preparation requirements and site conditions before application.</p><details className="mt-5 border border-neutral-200 bg-white p-5"><summary className="cursor-pointer text-sm font-semibold">Application & storage guidance</summary><p className="mt-4 text-sm leading-7 text-neutral-500">Use the current instructions for this material. Check substrate preparation, mixing, application conditions, curing and storage limits. Request the complete guidance from our team.</p></details></div></div></section>
    <section className="home-container py-12"><h2 className="home-heading">Explore other products.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products.filter(item => item.slug !== product.slug).map(item => <Link key={item.slug} href={`/products/${item.slug}`} className="border border-neutral-200 p-5 hover:border-brand-600"><Image src={`/images/${item.image}`} alt={item.name} width={100} height={130} className="mx-auto h-32 object-contain" /><h3 className="mt-4 text-sm font-semibold">{item.name}</h3><p className="mt-2 text-xs text-neutral-500">{item.category}</p></Link>)}</div></section>
    <section id="overview-inquiry" className="border-t border-neutral-200 bg-neutral-50 py-12"><div className="home-container grid gap-8 lg:grid-cols-2"><div><p className="home-eyebrow">Project support</p><h2 className="home-heading mt-3">Ask about {product.name}.</h2><p className="mt-5 text-sm leading-7 text-neutral-500">Share your application, specification and location. Our team can assist with product information and documentation.</p></div><QuoteForm /></div></section>
  </div>;
}
