'use client';

import { useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowLeft, ArrowRight, Building2, Check, ClipboardCheck, FileCheck2, FileText, Layers, MessageSquare, Package, Truck, UploadCloud, X, ZoomIn } from 'lucide-react';
import { projectStudies, type ProjectStudy } from '@/lib/projects';
import { QuoteForm } from './HomeInteractions';

export function ProjectDetail({ project }: { project: ProjectStudy }) {
  const [galleryIndex, setGalleryIndex] = useState(0);
  const lightboxRef = useRef<HTMLDialogElement>(null);
  const gallery = [
    { image: 'warehouse.jpg', title: 'Material handling & storage', subtitle: 'Illustrative logistics photography' },
    { image: project.slug === 'infrastructure' ? 'infrastructure.jpg' : 'tiling-application.jpg', title: 'Application context', subtitle: 'Representative application image' },
    { image: project.image, title: 'Built environment', subtitle: 'Illustrative architecture photography' },
  ];
  function inquire(request: string, upload = false) {
    window.dispatchEvent(new CustomEvent('quote-prefill', { detail: `${project.title}\n${request}` }));
    const section = document.getElementById('project-inquiry');
    section?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    if (upload) section?.querySelector<HTMLInputElement>('input[type="file"]')?.click();
    else section?.querySelector<HTMLInputElement>('input[name="company"]')?.focus({ preventScroll: true });
  }
  function openImage(index: number) { setGalleryIndex(index); lightboxRef.current?.showModal(); }
  function changeImage(direction: number) { setGalleryIndex(index => (index + direction + gallery.length) % gallery.length); }

  return <div className="homepage bg-white text-neutral-900">
    <section className="bg-surface-dark text-white">
      <div className="home-container flex flex-col justify-between gap-5 py-6 sm:flex-row sm:items-center"><nav aria-label="Breadcrumb" className="flex flex-wrap gap-3 text-xs text-neutral-400"><Link href="/" className="hover:text-white">Home</Link><span>/</span><Link href="/projects" className="hover:text-white">Projects</Link><span>/</span><span aria-current="page">{project.sector}</span></nav><nav aria-label="Project application sectors" className="flex flex-wrap gap-2">{projectStudies.map(study => <Link key={study.slug} href={`/projects/${study.slug}`} aria-current={study.slug === project.slug ? 'page' : undefined} className={`border px-3 py-2 text-[11px] font-medium transition-colors ${study.slug === project.slug ? 'border-brand-400 bg-brand-500/10 text-brand-300' : 'border-white/15 text-neutral-400 hover:border-brand-400 hover:text-white'}`}>{study.sector.split(' ')[0]}</Link>)}</nav></div>
      <div className="grid lg:grid-cols-[1.15fr_0.85fr]">
        <figure className="relative min-h-72 overflow-hidden sm:min-h-[420px] lg:min-h-[570px]"><Image src={`/images/${project.image}`} alt={`Illustrative ${project.sector.toLowerCase()} architecture`} fill loading="eager" fetchPriority="high" sizes="(max-width:1024px) 100vw, 58vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent" /><figcaption className="absolute bottom-6 left-6 right-6 flex flex-wrap items-center justify-between gap-3 text-[10px] uppercase tracking-widest text-white/80"><span>Application study / {project.sector}</span><span>Illustrative image</span></figcaption></figure>
        <div className="flex flex-col justify-center px-6 py-10 sm:px-10 lg:px-12 xl:px-16"><p className="home-eyebrow !text-brand-400">MAHAL FORET HAYAT / Project applications</p><h1 className="mt-5 max-w-lg text-3xl font-semibold leading-tight tracking-tight sm:text-4xl xl:text-5xl">{project.title}.</h1><p className="mt-5 max-w-md text-sm leading-7 text-neutral-300">{project.summary}</p><dl className="mt-7 grid grid-cols-2 gap-x-5 gap-y-5 border-t border-white/15 pt-6 text-xs"><div><dt className="text-neutral-500">Sector</dt><dd className="mt-2 text-neutral-200">{project.sector}</dd></div><div><dt className="text-neutral-500">Reference type</dt><dd className="mt-2 text-neutral-200">Illustrative application study</dd></div><div><dt className="text-neutral-500">Client & contractor</dt><dd className="mt-2 text-neutral-200">Published with verified references</dd></div><div><dt className="text-neutral-500">Supply timeline</dt><dd className="mt-2 text-neutral-200">Confirmed per project</dd></div></dl><a href="#technical-brief" className="mt-8 inline-flex items-center gap-3 text-xs font-semibold text-brand-300">Explore the technical approach<ArrowDown className="h-4 w-4" /></a></div>
      </div>
    </section>

    <section aria-label="Application study highlights" className="border-b border-neutral-200 bg-brand-50"><div className="home-container grid grid-cols-2 divide-x divide-neutral-200 lg:grid-cols-4">{[{ icon: Layers, value: '03', label: 'Material systems', detail: 'Coordinated in this study' }, { icon: ClipboardCheck, value: '04', label: 'Review stages', detail: 'From specification to site' }, { icon: Truck, value: 'Site-led', label: 'Delivery planning', detail: 'Access and sequencing reviewed' }, { icon: FileCheck2, value: 'Project-specific', label: 'Technical evidence', detail: 'Current documentation requested' }].map(item => <div key={item.label} className="px-4 py-7 sm:px-6"><item.icon className="mb-4 h-5 w-5 text-brand-700" strokeWidth={1.5} /><p className="text-xl font-semibold tracking-tight sm:text-2xl">{item.value}</p><h2 className="mt-2 text-xs font-semibold">{item.label}</h2><p className="mt-2 text-[11px] leading-5 text-neutral-500">{item.detail}</p></div>)}</div></section>

    <section id="technical-brief" className="home-container grid items-start gap-10 py-14 lg:grid-cols-[1fr_340px] lg:gap-14">
      <div className="min-w-0"><p className="home-eyebrow">01 / Technical brief</p><h2 className="home-heading mt-3">A system-led approach.</h2><p className="mt-6 text-sm leading-8 text-neutral-600">{project.scope}</p><div className="mt-7 border-l-2 border-brand-400 bg-neutral-50 p-6"><h3 className="text-sm font-semibold">Key considerations</h3><ul className="mt-4 space-y-4">{project.challenges.map(challenge => <li key={challenge} className="flex gap-3 text-sm leading-7 text-neutral-600"><Check className="mt-1.5 h-4 w-4 shrink-0 text-brand-700" />{challenge}</li>)}</ul></div>
        <div className="mt-12"><p className="home-eyebrow">02 / System implementation</p><h2 className="mt-3 text-2xl font-semibold tracking-tight">Materials working together.</h2><div className="mt-7 space-y-7">{project.systems.map((system,index) => <article key={system.name} className="flex gap-4 border-b border-neutral-200 pb-7"><span className="mt-1 text-xs font-semibold text-brand-700">0{index + 1}</span><div><h3 className="text-lg font-semibold">{system.name}</h3><p className="mt-3 text-sm leading-7 text-neutral-500">{system.detail}</p><Link href={system.href} className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-brand-700">Explore {system.product}<ArrowRight className="h-3.5 w-3.5" /></Link></div></article>)}</div></div>
        <div className="mt-12"><p className="home-eyebrow">03 / Material specification ledger</p><h2 className="mt-3 text-2xl font-semibold tracking-tight">The material plan at a glance.</h2><div className="mt-6 overflow-x-auto border border-neutral-200"><table className="project-material-ledger w-full text-left text-xs"><caption className="sr-only">Proposed material systems for this illustrative application study</caption><thead className="bg-surface-dark text-white"><tr><th className="px-5 py-4 font-medium">Product / system</th><th className="px-5 py-4 font-medium">Application</th><th className="px-5 py-4 font-medium">Quantity</th></tr></thead><tbody>{project.systems.map(system => <tr key={system.product} className="border-t border-neutral-200"><th scope="row" className="px-5 py-5 font-medium"><Link href={system.href} className="hover:text-brand-700">{system.product}</Link></th><td data-label="Application" className="px-5 py-5 text-neutral-500">{system.application}</td><td data-label="Quantity" className="px-5 py-5 text-neutral-500">To be specified</td></tr>)}</tbody></table></div><p className="mt-3 text-[11px] leading-6 text-neutral-500">Illustrative specification, not a record of supplied quantities. Final products and volumes depend on the approved project requirements.</p></div>
      </div>
      <aside aria-label="Project resources and consultation" className="space-y-5 lg:sticky lg:top-28"><div className="border border-neutral-200 bg-neutral-50 p-6"><FileText className="mb-5 h-7 w-7 text-brand-700" strokeWidth={1.5} /><h2 className="text-lg font-semibold">Project document hub</h2><p className="mt-3 text-xs leading-6 text-neutral-500">Request the current documents for your proposed material system.</p><div className="mt-5 space-y-3">{['Technical data sheet package', 'Application method statements', 'Applicable test certificates'].map(document => <button key={document} type="button" onClick={() => inquire(`Document request: ${document} for a similar project specification.`)} className="flex w-full items-center justify-between gap-3 border border-neutral-300 bg-white p-3 text-left text-xs leading-5 hover:border-brand-600"><span>{document}</span><ArrowRight className="h-4 w-4 shrink-0 text-brand-700" /></button>)}</div><p className="mt-4 text-[11px] leading-5 text-neutral-500">Project-approved files will be published when supplied and verified.</p></div><div className="bg-surface-dark p-6 text-white"><Building2 className="mb-5 h-7 w-7 text-brand-400" strokeWidth={1.5} /><h2 className="text-lg font-semibold">Working on a similar specification?</h2><p className="mt-3 text-xs leading-6 text-neutral-400">Share your tender requirements and application details. Start a focused technical conversation with our team.</p><button type="button" onClick={() => inquire('Please arrange a consultation about material selection and technical submittals for my project.')} className="home-button mt-5 w-full bg-brand-700 text-white hover:bg-brand-800">Request consultation<ArrowRight className="h-4 w-4" /></button></div></aside>
    </section>

    <section className="border-y border-neutral-200 bg-neutral-50 py-12"><div className="home-container"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="home-eyebrow">04 / Project coordination</p><h2 className="home-heading mt-3">From drawing to delivery.</h2></div><p className="max-w-sm text-xs leading-6 text-neutral-500">Four review stages to align the specification, material information and site plan.</p></div><ol className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['Define', 'Review the substrate, exposure, design details and performance requirements.'], ['Specify', 'Match the material system and request its current technical documentation.'], ['Coordinate', 'Plan quantities, storage, access and the preferred delivery sequence.'], ['Review', 'Confirm application guidance and required project inspections before work starts.']].map(([title,text],index) => <li key={title} className="border-t-2 border-brand-400 pt-5"><p className="text-xs font-semibold text-brand-700">0{index+1}</p><h3 className="mt-3 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-neutral-500">{text}</p></li>)}</ol></div></section>

    <section className="home-container py-14"><p className="home-eyebrow">05 / Visual context</p><h2 className="home-heading mt-3">The system in perspective.</h2><div className="mt-8 grid gap-5 sm:grid-cols-3">{gallery.map((item,index) => <figure key={item.title}><button type="button" aria-label={`Enlarge ${item.title.toLowerCase()} image`} onClick={() => openImage(index)} className="group relative block aspect-[4/3] w-full overflow-hidden bg-neutral-100"><Image src={`/images/${item.image}`} alt={item.subtitle} fill sizes="(max-width:640px) 100vw, 33vw" className="object-cover transition-transform duration-300 group-hover:scale-105" /><span className="absolute bottom-4 right-4 bg-white/90 p-2 text-neutral-700"><ZoomIn className="h-4 w-4" /></span></button><figcaption className="border-b border-neutral-200 py-4"><p className="text-sm font-semibold">{item.title}</p><p className="mt-2 text-[11px] text-neutral-500">{item.subtitle}</p></figcaption></figure>)}</div></section>

    <section className="bg-surface-dark py-12 text-white"><div className="home-container flex flex-col justify-between gap-7 lg:flex-row lg:items-center"><div><p className="home-eyebrow !text-brand-400">Your next specification</p><h2 className="mt-3 text-2xl font-semibold tracking-tight">Bring your project into focus.</h2><p className="mt-3 text-sm leading-7 text-neutral-400">Share your BOQ or speak with our team about a similar application.</p></div><div className="flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => inquire('Please review my project BOQ and match suitable material systems.', true)} className="home-button bg-brand-700 text-white hover:bg-brand-800"><UploadCloud className="h-4 w-4" />Upload your project BOQ</button><button type="button" onClick={() => inquire('Please contact me for a technical discussion about my project specification.')} className="home-button border border-white/25 hover:bg-white/10"><MessageSquare className="h-4 w-4" />Talk through your specification</button></div></div></section>
    <section id="project-inquiry" className="home-container grid gap-9 py-14 lg:grid-cols-[0.8fr_1.2fr]"><div><Package className="mb-5 h-7 w-7 text-brand-700" strokeWidth={1.5} /><p className="home-eyebrow">Project inquiry</p><h2 className="home-heading mt-3">Material decisions.<br />Made with a clear brief.</h2><p className="mt-5 max-w-md text-sm leading-7 text-neutral-500">Tell us about your project, the systems you are considering and the supporting documents you need.</p><Link href="/projects" className="mt-7 inline-flex items-center gap-2 text-xs font-medium text-brand-700"><ArrowLeft className="h-4 w-4" />Explore project applications</Link></div><QuoteForm /></section>

    <dialog ref={lightboxRef} aria-label="Project image gallery" onClick={event => { if (event.target === event.currentTarget) lightboxRef.current?.close(); }} onKeyDown={event => { if (event.key === 'ArrowRight') changeImage(1); if (event.key === 'ArrowLeft') changeImage(-1); }} className="m-auto w-[min(94vw,1100px)] max-w-none border border-neutral-700 bg-surface-dark p-4 text-white backdrop:bg-black/80"><div className="mb-4 flex items-center justify-between gap-4"><p className="text-sm">{gallery[galleryIndex].title}</p><button type="button" aria-label="Close project gallery" onClick={() => lightboxRef.current?.close()} className="p-2"><X className="h-5 w-5" /></button></div><Image src={`/images/${gallery[galleryIndex].image}`} alt={gallery[galleryIndex].subtitle} width={1300} height={900} className="max-h-[70dvh] w-full object-contain" /><div className="mt-4 flex items-center justify-between gap-3"><button type="button" aria-label="Previous gallery image" onClick={() => changeImage(-1)} className="p-2"><ArrowLeft className="h-5 w-5" /></button><p aria-live="polite" className="text-xs text-neutral-400">{galleryIndex+1} / {gallery.length} · {gallery[galleryIndex].subtitle}</p><button type="button" aria-label="Next gallery image" onClick={() => changeImage(1)} className="p-2"><ArrowRight className="h-5 w-5" /></button></div></dialog>
  </div>;
}
